version: 0.0
os: linux

files:
  - source: /src
    destination: /home/adamzhang22/CodeDeploy/divvy

permissions:
  - object: /home/adamzhang22/CodeDeploy/divvy/
    pattern: "**"
    owner: adamzhang22
    group: adamzhang22

  - object: /home/adamzhang22/CodeDeploy
    pattern: "divvy"
    owner: adamzhang22
    group: adamzhang22
    type:
      - directory

hooks:
  ApplicationStop:
    - location: bin/application_stop.sh
      timeout: 15
      runas: adamzhang22
  BeforeInstall:
    - location: bin/before_install.sh
      timeout: 120
      runas: adamzhang22
  AfterInstall:
    - location: bin/after_install.sh
      timeout: 1200
      runas: adamzhang22
  ApplicationStart:
    - location: bin/application_start.sh
      timeout: 120
      runas: adamzhang22
